const C=['#214f3e','#c58b3c','#39716c','#906d50'],S={mun:'all',year:2024,inegi:[],agri:[],geo:null,charts:{},map:null,layer:null};
const F=new Intl.NumberFormat('es-MX',{maximumFractionDigits:1}),M=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0});
function csv(t){let l=t.trim().split(/\r?\n/),h=l.shift().split(',');return l.map(x=>Object.fromEntries(h.map((k,i)=>[k,x.split(',')[i]||''])))}
const rows=()=>S.agri.filter(r=>(S.mun==='all'||r.municipio===S.mun)&&+r.anio===S.year),municipal=()=>S.inegi.filter(r=>S.mun==='all'||r.municipio===S.mun),sum=(k,a)=>a.reduce((n,r)=>n+(+r[k]||0),0);
function kpis(){let m=municipal(),a=rows().filter(r=>r.cultivo==='Total agrícola'),v=[[F.format(sum('poblacion_2020',m)),'personas','Población · INEGI 2020'],[F.format(sum('localidades_2020',m)),'localidades','Localidades · INEGI 2020'],[F.format(sum('superficie_sembrada_ha',a)),'hectáreas','Superficie sembrada · SIAP'],[M.format(sum('valor_produccion_miles_mxn',a)*1000),'pesos','Valor agrícola · SIAP']];document.querySelector('#kpis').innerHTML=v.map(x=>`<article class="kpi"><strong>${x[0]}</strong><small>${x[1]}</small><p>${x[2]}</p></article>`).join('')}
function chart(id,type,data,opt={}){S.charts[id]?.destroy();S.charts[id]=new Chart(id,{type,data,options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{boxWidth:9,font:{size:9}}}},scales:{x:{grid:{display:false},ticks:{font:{size:9}}},y:{beginAtZero:true,ticks:{font:{size:9}},grid:{color:'#e8ece9'}}},...opt}})}
function charts(){let m=municipal();chart('pop','bar',{labels:m.map(x=>x.municipio),datasets:[{label:'Población',data:m.map(x=>x.poblacion_2020),backgroundColor:C}]});let ys=[2020,2021,2022,2023,2024],ns=S.mun==='all'?S.inegi.map(x=>x.municipio):[S.mun];chart('trend','line',{labels:ys,datasets:ns.map((n,i)=>({label:n,data:ys.map(y=>sum('valor_produccion_miles_mxn',S.agri.filter(r=>r.municipio===n&&+r.anio===y&&r.cultivo==='Total agrícola'))),borderColor:C[i],backgroundColor:C[i],tension:.25}))});let g={};rows().filter(r=>r.cultivo!=='Total agrícola').forEach(r=>g[r.cultivo]=(g[r.cultivo]||0)+(+r.valor_produccion_miles_mxn||0));let a=Object.entries(g).sort((x,y)=>y[1]-x[1]);chart('crops','bar',{labels:a.map(x=>x[0]),datasets:[{label:'Valor (miles MXN)',data:a.map(x=>x[1]),backgroundColor:a.map((_,i)=>C[i%4])}]},{indexAxis:'y'})}
function table(){let q=document.querySelector('#search').value.toLowerCase(),a=rows().filter(r=>r.cultivo!=='Total agrícola'&&`${r.municipio} ${r.cultivo}`.toLowerCase().includes(q));document.querySelector('#rows').innerHTML=a.map(r=>`<tr><td>${r.anio}</td><td>${r.municipio}</td><td><b>${r.cultivo}</b></td><td>${F.format(r.superficie_sembrada_ha)}</td><td>${F.format(r.superficie_cosechada_ha)}</td><td>${r.produccion_t?F.format(r.produccion_t):'—'}</td><td>${r.rendimiento_t_ha?F.format(r.rendimiento_t_ha):'—'}</td><td>${F.format(r.valor_produccion_miles_mxn)}</td></tr>`).join('')||'<tr><td colspan="8">Sin registros.</td></tr>'}
function sty(f){return{color:'#fff',weight:2,fillColor:C[S.inegi.findIndex(x=>x.municipio===f.properties.municipio)],fillOpacity:S.mun==='all'||f.properties.municipio===S.mun?.82:.18}}
function map(){if(!S.map){S.map=L.map('map',{scrollWheelZoom:false}).setView([19.55,-103.65],9);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(S.map)}S.layer?.remove();S.layer=L.geoJSON(S.geo,{style:sty,onEachFeature:(f,l)=>{let d=S.inegi.find(x=>x.municipio===f.properties.municipio);l.bindPopup(`<b>${f.properties.municipio}</b><br>${F.format(d.poblacion_2020)} habitantes<br>${F.format(d.area_km2)} km²`);l.on('click',()=>{S.mun=f.properties.municipio;document.querySelector('#mun').value=S.mun;render(false)})}}).addTo(S.map);S.map.fitBounds(S.layer.getBounds())}
function render(remap=true){kpis();charts();table();remap?map():S.layer.setStyle(sty)}
async function init(){let [g,i,a]=await Promise.all([fetch('data/municipios_pbsv.geojson').then(r=>r.json()),fetch('data/inegi_municipios_2020.json').then(r=>r.json()),fetch('data/siap_agricola_2020_2024.csv').then(r=>r.text())]);S.geo=g;S.inegi=i;S.agri=csv(a);let mu=document.querySelector('#mun'),yr=document.querySelector('#year');i.forEach(x=>mu.insertAdjacentHTML('beforeend',`<option>${x.municipio}</option>`));[2024,2023,2022,2021,2020].forEach(x=>yr.insertAdjacentHTML('beforeend',`<option>${x}</option>`));mu.onchange=e=>{S.mun=e.target.value;render()};yr.onchange=e=>{S.year=+e.target.value;render(false)};document.querySelector('#search').oninput=table;document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.id).classList.add('active');if(b.dataset.id==='home')setTimeout(()=>S.map.invalidateSize(),30)});render()}
init().catch(e=>document.querySelector('main').innerHTML=`<p>${e.message}</p>`);
